# Demo Storage Configuration
storage.provider=LOCAL
storage.basePath=./qipi-demo-data
storage.baseUrl=file:///home/jjenus/workbench/apps/qipi/qipi-demo-data/
storage.signingKey=demo-signing-key-1772617294
